# Generated by Django 5.1.4 on 2024-12-17 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_network', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('pinterest', 'Pinterest'), ('linkedin', 'LinkedIn'), ('reddit', 'Reddit'), ('whatsapp', 'WhatsApp'), ('tumblr', 'Tumblr'), ('twitch', 'Twitch'), ('vimeo', 'Vimeo'), ('spotify', 'Spotify'), ('clubhouse', 'Clubhouse'), ('medium', 'Medium'), ('periscope', 'Periscope'), ('wechat', 'WeChat'), ('viber', 'Viber'), ('discord', 'Discord'), ('line', 'Line'), ('telegram', 'Telegram'), ('tiktok_lite', 'TikTok Lite'), ('triller', 'Triller'), ('dlive', 'DLive'), ('myspace', 'MySpace'), ('google_plus', 'Google+'), ('yelp', 'Yelp'), ('musical_ly', 'Musical.ly'), ('vine', 'Vine')], max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('followers', models.PositiveIntegerField()),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='influencers.influencer')),
            ],
        ),
    ]
