# Generated by Django 5.1.4 on 2024-12-22 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('influencers', '0006_rename_social_media_account_socialmediaaccount_account_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencer',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencers', to='influencers.manager'),
        ),
    ]
